name: phasor_diagram
version: 0.0.1+3
description: "Flutter package that provides a customizable solution for visualizing phasor diagrams in a three-phase electrical system"
repository: https://github.com/Arsenije95/phasor_diagram.git

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: "3.22.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  alchemist: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
