name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.17.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - run: flutter --version

      - run: flutter doctor -v

      - run: flutter pub get

#      - run: flutter test -v

      # Run the Flutter tests with Alchemist and verbose output
      - name: Run Flutter tests with Alchemist and verbose output
        run: flutter test -v > test_results.log

      # Upload the test results log as an artifact for debugging
      - name: Upload test logs
        uses: actions/upload-artifact@v3
        with:
          name: golden-test-logs
          path: test_results.log

      # Optionally, upload the golden images folder (if required for debugging)
      - name: Upload golden images
        uses: actions/upload-artifact@v4
        with:
          name: golden-test-images
          path: test/goldens/
