name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.17.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - run: flutter --version

      - run: flutter pub get

      - run: xvfb-run -s "-screen 0 1280x1024x24" flutter test
